title: All things Software
locale: en_US
subtitle: CICD, JAVA, WEB, CLOUD
name: "Joachim Prinzbach"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://joachimprinzbach.github.io"
repository: "joachimprinzbach/joachimprinzbach.github.io"
twitter_username: johaaachim
twitter:
  username: "johaaachim"
github_username:  joachimprinzbach
search: true

remote_theme: "mmistakes/minimal-mistakes@4.18.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: "default"

include: ["_pages"]

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      author_profile: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      read_time: true
      comments: true
      author_profile: true
      related: true

author:
  name     : "Joachim Prinzbach"
  avatar   : "/assets/images/bio.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Switzerland / Germany"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/johaaachim"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joachimprinzbach"
